### ISSUE TITLE
跑flashformer出现重复参数值传递错误

### ISSUE THREAD

**Issue by wml161518** [wzhwzhwzh0921/S-D-Mamba#13]
您好，作者大大，我在复现你在flashformer、flowformer加入mamba块的对比实验时，出现了如下dropout值重复传递导致模型初始化失败的问题。
```
File "/home/wml/pycode/S-D-Mamba-main/model/Flashformer.py", line 26, in __init__
    [
  File "/home/wml/pycode/S-D-Mamba-main/model/Flashformer.py", line 27, in <listcomp>
    EncoderLayer(
TypeError: __init__() got multiple values for argument 'dropout'
```
想向您请教一下原因

**Comment by wzhwzhwzh0921** [comment]
感谢您尝试复现我们的实验结果！很抱歉，我们并未详细检查这些实验的代码，感谢指出错误！这个错误的发生原因是在encoder层，多传入了一个参数，您可以检查一下，在初始化的mamba block 下面有一个额外的参数 “1”。

我们正在对论文进行最后一轮检查和修改，并会尽快将所有实验的代码开源。

**Comment by wml161518** [comment]
感谢您的回复，不过删除额外参数“1”之后， 出现了新的错误
`TypeError: forward() got an unexpected keyword argument 'attn_mask'`
期待你们检查修改后的开源实验代码，我会follow你们，你们的idea让我很有启发

**Comment by wzhwzhwzh0921** [comment]
已经更新好了
