### ISSUE TITLE
TypeError: causal_conv1d_fwd(): incompatible function arguments.

### ISSUE THREAD

**Issue by syrGitHub** [wzhwzhwzh0921/S-D-Mamba#15]
作者您好，我在运行代码时出现了这个问题，请问您知道是什么原因嘛？
![微信图片_20240416225359](https://github.com/wzhwzhwzh0921/S-D-Mamba/assets/31035074/d4e9dafb-887b-44ae-b846-39d2a15ff86e)

**Comment by wzhwzhwzh0921** [comment]
您好！看起来是mamba block中的selective机制报错，不过我这边没有遇到过，你可以去Mamba的Repository里翻看一下issue，应该会有类似的问题。

**Comment by uxhao-o** [comment]
我最开始也出现了这个问题，现在已经解决了。
我的环境
cuda 11.8 
python 3.10.13 
pytorch 2.1.1 
causal_conv1d 1.1.1 
mamba-ssm 1.2.0.post1 
``` 
pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118 
pip install causal_conv1d==1.1.1 
pip install mamba-ssm==1.2.0.post1 
```

**Comment by syrGitHub** [comment]
非常感谢大家的建议，也去Mamba的Repository里翻看了issue，是版本的问题~

**Comment by caokaibin** [comment]
The issue still exists after install  causal_conv1d==1.1.1 and mamba-ssm==1.2.0.post1. Which version do  you use?

**Comment by Joeland4** [comment]
> 我最开始也出现了这个问题，现在已经解决了。 我的环境 cuda 11.8 python 3.10.13 pytorch 2.1.1 causal_conv1d 1.1.1 mamba-ssm 1.2.0.post1
> 
> ```
> pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118 
> pip install causal_conv1d==1.1.1 
> pip install mamba-ssm==1.2.0.post1 
> ```

哥们，我在mamba仓库也看到你，用了你的环境可以运行mamba里的test程序，但这个时序还是报错，奇怪？
